---

#email settings
email_subject: Post_check report
email_host: smtp.hy-vee.com
email_from: root@localhost
email_to: yagamoorthy.s@hy-vee.com
#email_to: infralinux@hy-vee.com

#random settings
csv_path: /tmp
csv_filename: post_checks.csv
headers: Hostname,Ip Address,service status,Uptime
